# -*- coding: utf-8 -*-
"""threading_parallel_computing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f641rzIsjX-rJ9h2WwgMDie0_RLjDbV5
"""

from threading import Thread, Lock
from time import sleep
import threading

lock = Lock()

def room(str):
    lock.acquire(timeout=2)
    print(str, "Enter the room")

    # sleep(2)

    print(str, 'exit the room')
    lock.release()

if __name__ == "__main__":
    threads = []

    for i in range(1, 6):
        person = threading.Thread(target=room, args=(f"I am person {i} ",))
        threads.append(person)
        person.start()

    for person in threads:
        person.join()


print("the room is empty!!!")